import { VueConstructor } from 'vue';
import * as directives from './directives';
import Anchor from '../packages/Anchor/index';
import { Button, ButtonGroup } from '../packages/Button/index';
import Card from '../packages/Card/index';
import Drawer from '../packages/Drawer/index';
import Dropdown from '../packages/Dropdown/index';
import ImagePreview from '../packages/ImagePreview/index';
import { Input, InputGroup } from '../packages/Input/index';
import { List, ListItem, ListGroup, ListItemGroup } from '../packages/List/index';
import Mask from '../packages/Mask/index';
import Modal from '../packages/Modal/index';
import Pagination from '../packages/Pagination/index';
import Rate from '../packages/Rate/index';
import Row from '../packages/Row/index';
import Snackbar from '../packages/Snackbar/index';
import TableSimple from '../packages/TableSimple/index';
import Tag from '../packages/Tag/index';
import Textarea from '../packages/Textarea/index';
import Tooltip from '../packages/Tooltip/index';
import MaterialInput from '../packages/MaterialInput/index';
interface InstallationOptions {
    size?: string;
}
declare const _default: {
    install: (Vue: VueConstructor<Card>, options?: InstallationOptions) => void;
    directives: typeof directives;
    Anchor: typeof Anchor;
    Badge: import("vue/types/vue").ExtendedVue<Card, {}, {}, {}, Record<never, any>>;
    Button: typeof Button;
    ButtonGroup: typeof ButtonGroup;
    Card: VueConstructor<Card>;
    Carousel: VueConstructor<Card>;
    CarouselItem: VueConstructor<Card>;
    CarouselIndicator: VueConstructor<Card>;
    Catalogue: VueConstructor<Card>;
    CatalogueItem: VueConstructor<Card>;
    Cell: VueConstructor<Card>;
    CellGroup: VueConstructor<Card>;
    Checkbox: VueConstructor<Card>;
    CheckboxGroup: VueConstructor<Card>;
    Col: VueConstructor<Card>;
    Drawer: typeof Drawer;
    Dropdown: typeof Dropdown;
    DropdownMenu: VueConstructor<Card>;
    Form: VueConstructor<Card>;
    FilterSection: VueConstructor<Card>;
    FilterSectionGroup: VueConstructor<Card>;
    FilterSectionItem: VueConstructor<Card>;
    FixedSection: VueConstructor<Card>;
    Heading: VueConstructor<Card>;
    Icon: VueConstructor<Card>;
    Image: VueConstructor<Card>;
    ImagePreview: typeof ImagePreview;
    Input: typeof Input;
    InputGroup: typeof InputGroup;
    Layout: VueConstructor<Card>;
    List: typeof List;
    ListItem: typeof ListItem;
    ListGroup: typeof ListGroup;
    ListItemGroup: typeof ListItemGroup;
    Loading: import("vue/types/vue").ExtendedVue<Card, {}, {}, {}, Record<string, any>>;
    Mask: typeof Mask;
    Masonry: VueConstructor<Card>;
    Modal: typeof Modal;
    MasonryItem: VueConstructor<Card>;
    Navigation: VueConstructor<Card>;
    Option: VueConstructor<Card>;
    Pagination: typeof Pagination;
    Progress: VueConstructor<Card>;
    ProgressCircle: VueConstructor<Card>;
    Radio: VueConstructor<Card>;
    RadioButton: VueConstructor<Card>;
    RadioGroup: VueConstructor<Card>;
    Rate: typeof Rate;
    Row: typeof Row;
    Select: VueConstructor<Card>;
    SubHeader: VueConstructor<Card>;
    Switch: VueConstructor<Card>;
    Scrollbar: VueConstructor<Card>;
    SildeGroup: VueConstructor<Card>;
    Snackbar: typeof Snackbar;
    State: import("vue/types/vue").ExtendedVue<Card, {}, {}, {}, Record<never, any>>;
    Tabs: VueConstructor<Card>;
    Tab: VueConstructor<Card>;
    Table: VueConstructor<Card>;
    TableSimple: typeof TableSimple;
    Tag: typeof Tag;
    Textarea: typeof Textarea;
    Tooltip: typeof Tooltip;
    MaterialInput: typeof MaterialInput;
};
export default _default;
