import { CreateElement } from 'vue';
import MzSize from 'manzhai-ui/src/mixins/MzSize';
import MzColor from 'manzhai-ui/src/mixins/MzColor';
declare const MzSnackbar_base: import("vue-class-component/lib/declarations").VueClass<MzSize & MzColor>;
export default class MzSnackbar extends MzSnackbar_base {
    readonly visible: boolean;
    readonly placement: 'top' | 'top-start' | 'top-end' | 'center' | 'bottom' | 'bottom-start' | 'bottom-end';
    readonly timeout: number;
    readonly icon: string;
    readonly content: string;
    readonly fixed: boolean;
    readonly absolute: boolean;
    readonly vertical: boolean;
    readonly appendToBody: boolean;
    readonly offset: [number, number];
    readonly zIndex: number;
    readonly radius: string;
    timer: number | null;
    mZIndex: number | null;
    get placementList(): string[];
    get transitionName(): "mz-zoom" | "mz-y-zoom";
    get offsetStyles(): Record<string, any>;
    renderMain(): JSX.Element;
    render(h: CreateElement): JSX.Element;
    initZIndex(): void;
    initTimer(visible: boolean): void;
    handleVisibleChange(visible: boolean): void;
    destroyed(): void;
}
export {};
