import { CreateElement } from 'vue';
import MzSize from 'manzhai-ui/src/mixins/MzSize';
import FormElement from 'manzhai-ui/src/mixins/FormElement';
declare const MzInput_base: import("vue-class-component/lib/declarations").VueClass<MzSize & FormElement>;
export default class MzInput extends MzInput_base {
    readonly value: string | number;
    readonly type: string;
    readonly readonly: boolean;
    readonly placeholder: string;
    readonly ripple: boolean | object;
    readonly autocomplete: 'on' | 'off';
    readonly maxlength: string | number;
    readonly max: any;
    readonly min: any;
    readonly step: any;
    readonly rounded: boolean;
    readonly prefix: string;
    readonly suffix: string;
    readonly flat: boolean;
    readonly shadow: boolean;
    readonly inputRef: HTMLInputElement;
    isComposing: boolean;
    focused: boolean;
    renderIcon(position: 'prefix' | 'suffix'): JSX.Element | undefined;
    renderInput(): JSX.Element;
    render(h: CreateElement): JSX.Element;
    onCompositionstart(event: CompositionEvent): void;
    onCompositionUpdate(event: CompositionEvent): void;
    onCompositionEnd(event: CompositionEvent): void;
    onInput(event: InputEvent | CompositionEvent): void;
    focus(): void;
    blur(): void;
    onFocus(event: InputEvent): void;
    onBlur(event: InputEvent): void;
    onChange(event: InputEvent): void;
}
export {};
